<?xml version="1.0"?>


<robot xmlns:xacro="http://ros.org/wiki/xacro">

	<xacro:macro name="yorat_base" params="name">

		<link name="base_link">
			<inertial>
				<mass value="${base_mass}" />
				<origin xyz="0 0 -${base_z_size/2}" />
				<!--inertia  ixx="0.6" ixy="-0.002364" ixz="-0.01197" iyy="1.7386" iyz="-0.0001544" izz="2.0296" /-->
				<inertia  ixx="0.5" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="0.1" />
			</inertial>
		
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
	         		<box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
	      		</geometry>
	      		<material name="">
    				<color rgba="${0/255} ${255/255} ${0/255} 1.0"/>
  				</material>
			</visual>
		
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
	         		<box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
	      		</geometry>
			</collision>
		</link>

		<!-- Base footprint is on the ground under the robot -->
  		<link name="base_footprint_link"/>

		<joint name="base_footprint_joint" type="fixed">
			<origin xyz="0 0 ${base_z_size/2}" rpy="0 0 0" />
		    <parent link="base_link" />
		    <child link="base_footprint_link" />
		</joint>


		<!-- Caster Ball -->
		<link name="caster_wheel">

			<inertial>
	      		<origin
	        		xyz="0 0 0"
					rpy="0 0 0"/>
	      		<mass 
	      			value="${caster_mass}" />
	      		<inertia
	        		ixx="1.0001"
			        ixy="0"
			        ixz="0"
			        iyy="1.0001"
			        iyz="0"
			        izz="1.0" />
			</inertial>

			<visual>
	      		<origin
	        		xyz="0 0 0"
					rpy="0 0 0"/>
		      	<geometry>
		         	<!--box size="${caster_x_size} ${caster_y_size} ${base_z_offset}"/--> <!--sphere radius="0.0035"/-->
		         	<!--cylinder length="${caster_y_size}" radius="${base_z_offset/2}" /-->
		         	<sphere radius="${base_z_offset/2}"/>
		      	</geometry>
		      	<material name="">
    				<color rgba="${45/255} ${45/255} ${45/255} 1.0"/>
  				</material>
			</visual>

			<collision>
	      		<origin
	        		xyz="0 0 0"
					rpy="0 0 0"/>
		      	<geometry>
		         	<!--box size="${caster_x_size} ${caster_y_size} ${base_z_offset}"/--> <!--sphere radius="0.0035"/-->
		         	<!--cylinder length="${caster_y_size}" radius="${base_z_offset/2}" /-->
		         	<sphere radius="${base_z_offset/2}"/>
		      	</geometry>
		      	<surface>
			      <friction>
			        <ode>
			          <mu>0</mu>
			          <mu2>0</mu2>
			          <slip1>1.0</slip1>
			          <slip2>1.0</slip2>
			        </ode>
			      </friction>
			    </surface>
			</collision>
		</link>

		<!-- Caster Wheel Joint -->
		<joint name="base_caster_joint" type="fixed">
			<parent link="base_link"/>
			<child link="caster_wheel"/>
	    	<origin xyz="${caster_x_pos} 0 -${base_z_size/2 + base_z_offset/2}"
	    		    rpy="0 0 0"/>
	    	<!--origin xyz="${base_x_size/2 - caster_x_size} 0 -${base_z_size/2 + base_z_offset/2}"
	    		    rpy="0 0 0"/-->
	    	<!--origin xyz="${base_x_size/2 - caster_x_size} 0 -${base_z_size/2 + base_z_offset/2}"
	    		    rpy="${PI/2} 0 0"/-->
	    	<axis xyz="0 0 0" />
		</joint>

		<gazebo reference="base_link">
	    	<material>Gazebo/Green</material>
		</gazebo>

		<gazebo reference="caster_wheel">
		    <material>Gazebo/DarkGrey</material>
		</gazebo>


		</xacro:macro>

</robot>